plugins {
    id 'java'
}

group = 'dev.ragger'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://repo.runelite.net'
    }
}

dependencies {
    implementation 'net.runelite:cache:1.12.34.1'
    implementation 'net.runelite:runelite-api:1.12.34.1'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'org.slf4j:slf4j-simple:2.0.16'
}

tasks.register('dumpCollision', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpCollision'
}

tasks.register('dumpWater', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpWater'
}

tasks.register('dumpMapTiles', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpMapTiles'
    jvmArgs = ['-Xmx2g']
}

tasks.register('dumpGameVars', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpGameVars'
}

tasks.register('dumpNpcDefinitions', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpNpcDefinitions'
}

tasks.register('dumpObjectDefinitions', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpObjectDefinitions'
}

tasks.register('dumpObjectLocations', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.DumpObjectLocations'
    jvmArgs = ['-Xmx2g']
}

tasks.register('inspectObjects', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'dev.ragger.cachedump.InspectObjects'
    jvmArgs = ['-Xmx2g']
}
